### ISSUE TITLE
Post and Homepage layout update

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-energynewsnetwork#49]
Blog roll of one-wide column to replace the current page-bottom grid 3/2 post layout on homepage and other locations.
This will include:
- Left thumbnail
- Headline
- Excerpt

**Comment by benlk** [comment]
From https://secure.helpscout.net/conversation/692736424/2743/?folderId=2051037, Ken's mockup:

![homepage mockup version 2 (2)](https://user-images.githubusercontent.com/1754187/56376776-cf47de00-61d6-11e9-9059-f345dd346b3d.png)

**Comment by benlk** [comment]
Before, the homepage was a row with a span8/span4 split above, then a span12 section of the alternating 3/2 rows of posts. Now, this layout will be a plain span8/span4 split occupying the whole height of the page.

**Comment by benlk** [comment]
The homepage changes in #52 are ready for the first pass of client review, but those changes only encompass the homepage-bottom changes. It doesn't affect the image alignment from #50 or the layout of region pages, which share a layout with the homepage. If we were to submit it to the client today, we'd want to frame it as:

> Does this specific section look correct? We'd like to make sure before applying those changes elsewhere."

**Comment by benlk** [comment]
The homepage bottom changes have been copied to the region pages, and the image alignments in #50 are added.

**Comment by MirandaEcho** [comment]
Updates from client review:
For sidebar content: Just the links and the newsletter. Links at the top, signup box, and then the newsletter roundup.

Also, to make sure we're on the same page, the existing boxes for the email digests need to be redesigned; we have a suggestion in the mockup. The existing boxes are confusing and use up too much real estate.

**Comment by benlk** [comment]
I'll copy that comment into #51, which is the sidebar styles issue.
