### ISSUE TITLE
Sidebar style changes

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-energynewsnetwork#51]
Sidebar style changes as determined by mock-up to be provided by client prior to implementation

**Comment by benlk** [comment]
Did we get a mockup for this?

**Comment by MirandaEcho** [comment]
@Ben I got a response from Ken, and it seems to be the same mockup as the homepage, so I'm guessing that sidebar in the mockup reflects the changes he wanted to make. He also said: 

This is a rough sketch, just to communicate the idea so we don't expect it to look exactly the same.

We talked with Ben about having parts of this drop off for the mobile version.

![homepage mockup version 2 (2)](https://user-images.githubusercontent.com/48263361/56906251-734b4800-6a67-11e9-9cfd-1e209a73b401.png)

**Comment by benlk** [comment]
In testing in #55.
