### ISSUE TITLE
Sidebar Feedback from Ken

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-energynewsnetwork#57]
- [x] Labels in the sidebar are slightly different typeface than the labels in the main column. They should either be identical or notably different. Identical is probably better.
- [x] Use "Top Headlines" instead of "Curated Headlines" at the top.
- [x] Signup box and the daily email digests should be grouped together as one unit with the same color screen behind them (that wasn't very clear in the mockup).
- [x] Have the archived digests in the same order as the checkboxes on the signup form. Use "U.S." in both locations if possible.
- [x] Link at the end of the sidebar, "More daily email digest archives" pointing to: /category/digest/

**Comment by benlk** [comment]
This was a mix of config and style changes; which are deployed now.
