### ISSUE TITLE
Support - Remove old signup form

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-energynewsnetwork#64]
Issue: Subscribers are turning up on an old Mailchimp list- investigate where they’re coming from

HelpScout thread: https://secure.helpscout.net/conversation/997639429/4633/

**Comment by benlk** [comment]
From that thread, we're removing this:

https://github.com/INN/umbrella-energynewsnetwork/blob/5edb6f2112850a887f1c8f87af08123f172cdfdb/wp-content/themes/midwestenergynews/inc/newsletter-shortcode.php#L20-L29

**Comment by benlk** [comment]
This is now deployed to staging. Compare:

-  the staging URL: https://usenergystage.wpengine.com/2014/12/18/midwest/report-sees-bright-future-for-renewable-energy-in-minnesota/
- the live URL: https://energynews.us/2014/12/18/midwest/report-sees-bright-future-for-renewable-energy-in-minnesota/
