### ISSUE TITLE
Support - Remove digests from more posts feed

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-energynewsnetwork#65]
Issue: On Regional pages, when you click "more posts" at the end, it starts pulling in digests as well as posts. There should only be posts on these pages. 

HelpScout thread: https://secure.helpscout.net/conversation/998486977/4637/

**Comment by benlk** [comment]
Reproducible on the midwest region, and after clicking More Posts a few times you can confirm the existence of roundups with the `#homepage-bottom article:not(.type-post)` CSS selector

**Comment by benlk** [comment]
Deployed to https://usenergystage.wpengine.com/ now.
