### ISSUE TITLE
Digest Search Page modifications, part 2

### ISSUE THREAD

**Issue by benlk** [INN/umbrella-energynewsnetwork#94]
Individual result items:
- [ ] create a custom partial for use on this page
- [ ] remove excerpts
- [ ] add publish date

Overall behavior:
- [ ] sort and group results by region term
    - [ ] if a post is in multiple regions, does it show in one or in all regions?
    - [ ] What order do regions appear in? Can this order be hardcoded, or does it need to be configurable by ENN?
- [ ] before each group, output a header showing that region name
    - [ ] if there is only one group on the page, do we need to show that name?

**Comment by MirandaEcho** [comment]
Ken opted for the shorter approach: only removing the excerpts form the digest page list (on only this category, not all categories) and adding in the date for each post.

**Comment by benlk** [comment]
I'll make a separate issue for that, then.
